# Sample usage: make runserver
runserver:
	python manage.py runserver

# Sample usage: make migrate
migrate:
	python manage.py migrate

# Sample usage: make makemigrations app=<your_app_name>
# Example: make makemigrations app=my_app
makemigrations:
	python manage.py makemigrations $(app)

# Sample usage: make shell
shell:
	python manage.py shell
